# postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: opaque
data:
  POSTGRES_DB: Zmxhc2tkYg==
  POSTGRES_USER: Zmxhc2t1c2Vy
  POSTGRES_PASSWORD: Zmxhc2twYXNzd29yZA==

