apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask
spec:
  type: NodePort  # Exposes the service on a NodePort
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30007  # Ensure this port is available on Minikube